sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
install:
  - pip install tox-travis
  - pip install coveralls
script: tox
after_success:
  - coveralls
jobs:
  fast_finish: true
  include:
  - stage: deploy
    python: 3.6
    before_install:
    # This must prevent further job progress
    - |
      if [ -z "$TRAVIS_TAG" ]
      then
        echo Not building wheels
        exit 0
      fi
    before_deploy:
    - pip install -r build_requirements.txt
    deploy:
    - provider: pypi
      distributions: sdist
      user: penguinolog
      password:
        secure: cqEVQkkhyEqFyvf0aPLuCRRneV8Hc6ZTPKDxdbQHzfFSb0APp268/z2ASKtqFx5jydogFr+IZ9RE5biOYAMLDxTUtmSjvDIjqbtmm7QrJFWLVPGi5TUtGettsz18pzFVQudERQ7k8EhGnHpvIeGA9IEmSwC3+1xseZrHIBnOnAMRxnPIJbgJtkKno8nazqxeRcdm5KOUrH0Bb4UEtVdL8KPOEXjTFj4etLAQzdrkGjZsUTxTY7CTuckSCXfsqIcDmwUdgUkFQANDu2HtxoR+u6eVJ1J4XPfyaEWd2KYMmfXxKNGosmznict37LiQmPCpWwyw5jpJ2cPByav7LJZCjymH304SBpVVnIu1aeQtWa3TG/CSZ4nJizJaCNHSzJryw8CJFrgYwByPdSM3nQo/EqZUv/yJKqYMkkvnZw8569MApY+mTSiYcj549duppICMeUl465+Un7PhscK7fFvzGzy/lIA7uNCVtX9uvwE8HZrsxeCUk2zAEGXwzGzYZrQ0mN/ufwouWPt75BWErUEDn1Azr0+6zrBqdXmvDj8mdKwQdasB0ATWTsy5sH/ZJzutctA018CDY9pa1vrbLvQNHVwCYjXxoYzCN6Jxqh5PDeHXm/DyBSSQK+omxfYpS/Aj/h0GvvTTYMHhEAoD7bxKM4tclgtE8aMDu4POI5cBtsA=
      on:
        python: 3.6
        tags: true
      skip_upload_docs: true
      skip_cleanup: true
