sudo: false
language: python
os: linux
python:
- 2.7
- 3.4
- 3.5
- &mainstream_python 3.6
- pypy2.7-5.8.0
- pypy3.5-5.8.0
install:
- &upgrade_python_toolset pip install --upgrade pip setuptools wheel
- pip install tox-travis
- pip install coveralls
script: tox
after_success:
- coveralls
jobs:
  fast_finish: true
  include:
  - stage: Test packaged
    python: *mainstream_python
    install:
    - *upgrade_python_toolset
    - pip install pytest pytest-sugar
    - pip install -r build_requirements.txt
    script:
    - python setup.py bdist_wheel
    - pip install BinField --no-index -f dist
    - py.test -vv test
    after_success: skip
  - stage: deploy
    python: *mainstream_python
    services:
    - docker
    before_install:
    # This must prevent further job progress
    - |
      if [ -z "$TRAVIS_TAG" ]
      then
        echo Not building wheels
        exit 0
      fi
    install: skip
    script:
    - ./tools/run_docker.sh "BinField"
    after_success: skip
    before_deploy:
    - pip install -r build_requirements.txt
    deploy:
    - provider: pypi
      # `skip_cleanup: true` is required to preserve binary wheels, built
      # inside of manylinux1 docker container during `script` step above.
      distributions: sdist
      user: penguinolog
      password:
        secure: cqEVQkkhyEqFyvf0aPLuCRRneV8Hc6ZTPKDxdbQHzfFSb0APp268/z2ASKtqFx5jydogFr+IZ9RE5biOYAMLDxTUtmSjvDIjqbtmm7QrJFWLVPGi5TUtGettsz18pzFVQudERQ7k8EhGnHpvIeGA9IEmSwC3+1xseZrHIBnOnAMRxnPIJbgJtkKno8nazqxeRcdm5KOUrH0Bb4UEtVdL8KPOEXjTFj4etLAQzdrkGjZsUTxTY7CTuckSCXfsqIcDmwUdgUkFQANDu2HtxoR+u6eVJ1J4XPfyaEWd2KYMmfXxKNGosmznict37LiQmPCpWwyw5jpJ2cPByav7LJZCjymH304SBpVVnIu1aeQtWa3TG/CSZ4nJizJaCNHSzJryw8CJFrgYwByPdSM3nQo/EqZUv/yJKqYMkkvnZw8569MApY+mTSiYcj549duppICMeUl465+Un7PhscK7fFvzGzy/lIA7uNCVtX9uvwE8HZrsxeCUk2zAEGXwzGzYZrQ0mN/ufwouWPt75BWErUEDn1Azr0+6zrBqdXmvDj8mdKwQdasB0ATWTsy5sH/ZJzutctA018CDY9pa1vrbLvQNHVwCYjXxoYzCN6Jxqh5PDeHXm/DyBSSQK+omxfYpS/Aj/h0GvvTTYMHhEAoD7bxKM4tclgtE8aMDu4POI5cBtsA=
      on:
        tags: true
      skip_upload_docs: true
      skip_cleanup: true

cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
